apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: vote-app
spec:
  selector: 
    app: vote
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000  # Vote app runs on port 5000