apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: vote-app
spec:
  type: NodePort
  selector:
    app: result
  ports:
  - name: result-port
    port: 80  # External port
    targetPort: 3000  # Container port
